name: scivis-2025
channels:
  - conda-forge
  - menpo
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - jupyterlab
  - mayavi
  - ipyvolume
  - ipympl
  - trame
  - pip:
    - pyvista[jupyter]
